"""Seed Infrastructures (25 laboratories - 5 per institute)

This seed creates laboratory infrastructures for each ISI/CIS institute.

Revision ID: infrastructures_seed
Create Date: 2026-01-24 12:00:00
"""
from __future__ import annotations

import json
from typing import Iterable
from sqlalchemy import text

# Inline stable IDs to avoid cross-module import issues in Docker
INSTITUTE_IDS = {
    'ISI_SVP': 'a1000000-0000-0000-0000-000000000001',
    'ISI_QV': 'a1000000-0000-0000-0000-000000000002',
    'ISI_BF': 'a1000000-0000-0000-0000-000000000003',
    'ISI_II': 'a1000000-0000-0000-0000-000000000004',
    'CIS_SO': 'a1000000-0000-0000-0000-000000000005',
}


# Stable IDs for infrastructures
INFRA_IDS = {
    # ISI SVP Labs (5)
    'LAB_SVP_1': 'c1000000-0000-0000-0000-000000000001',
    'LAB_SVP_2': 'c1000000-0000-0000-0000-000000000002',
    'LAB_SVP_3': 'c1000000-0000-0000-0000-000000000003',
    'LAB_SVP_4': 'c1000000-0000-0000-0000-000000000004',
    'LAB_SVP_5': 'c1000000-0000-0000-0000-000000000005',
    # ISI QV Labs (5)
    'LAB_QV_1': 'c1000000-0000-0000-0000-000000000006',
    'LAB_QV_2': 'c1000000-0000-0000-0000-000000000007',
    'LAB_QV_3': 'c1000000-0000-0000-0000-000000000008',
    'LAB_QV_4': 'c1000000-0000-0000-0000-000000000009',
    'LAB_QV_5': 'c1000000-0000-0000-0000-000000000010',
    # ISI B&F Labs (5)
    'LAB_BF_1': 'c1000000-0000-0000-0000-000000000011',
    'LAB_BF_2': 'c1000000-0000-0000-0000-000000000012',
    'LAB_BF_3': 'c1000000-0000-0000-0000-000000000013',
    'LAB_BF_4': 'c1000000-0000-0000-0000-000000000014',
    'LAB_BF_5': 'c1000000-0000-0000-0000-000000000015',
    # ISI II Labs (5)
    'LAB_II_1': 'c1000000-0000-0000-0000-000000000016',
    'LAB_II_2': 'c1000000-0000-0000-0000-000000000017',
    'LAB_II_3': 'c1000000-0000-0000-0000-000000000018',
    'LAB_II_4': 'c1000000-0000-0000-0000-000000000019',
    'LAB_II_5': 'c1000000-0000-0000-0000-000000000020',
    # CIS SO Labs (5)
    'LAB_SO_1': 'c1000000-0000-0000-0000-000000000021',
    'LAB_SO_2': 'c1000000-0000-0000-0000-000000000022',
    'LAB_SO_3': 'c1000000-0000-0000-0000-000000000023',
    'LAB_SO_4': 'c1000000-0000-0000-0000-000000000024',
    'LAB_SO_5': 'c1000000-0000-0000-0000-000000000025',
}

INFRASTRUCTURES = [
    # ISI SVP Labs (5)
    {
        'id': INFRA_IDS['LAB_SVP_1'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Laboratório de Simulação Virtual',
        'name': 'Virtual Simulation Lab',
        'descricao': 'Laboratório equipado com sistemas de simulação de processos industriais, CAD/CAM/CAE e modelagem 3D para manufatura digital.',
        'email_laboratorio': 'lab.simulacao@isisvp.senai.br',
        'email_responsavel': 'carlos.silva@isisvp.senai.br',
        'area_predial_m2': 250,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.5,
        'maturidade_laboratorial': 4.3,
        'plataformas_tecnologicas': ['Simulação', 'CAD/CAM', 'Digital Twin'],
        'areas_conhecimento': ['Engenharia de Produção', 'Ciência da Computação'],
        'equipamentos': [
            {'nome': 'Servidor de Simulação', 'marca': 'Dell', 'modelo': 'PowerEdge R750', 'quantidade': 3},
            {'nome': 'Estação de Trabalho CAD', 'marca': 'HP', 'modelo': 'Z8 G4', 'quantidade': 10},
        ],
    },
    {
        'id': INFRA_IDS['LAB_SVP_2'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Laboratório de Manufatura 4.0',
        'name': 'Industry 4.0 Manufacturing Lab',
        'descricao': 'Linha de produção piloto com robôs colaborativos, sensores IoT e sistemas de controle integrados.',
        'email_laboratorio': 'lab.manufatura@isisvp.senai.br',
        'email_responsavel': 'marina.costa@isisvp.senai.br',
        'area_predial_m2': 400,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.2,
        'maturidade_laboratorial': 4.0,
        'plataformas_tecnologicas': ['IoT Industrial', 'Robótica', 'Automação'],
        'areas_conhecimento': ['Engenharia Mecatrônica', 'Automação Industrial'],
        'equipamentos': [
            {'nome': 'Robô Colaborativo', 'marca': 'Universal Robots', 'modelo': 'UR10e', 'quantidade': 2},
            {'nome': 'PLC Industrial', 'marca': 'Siemens', 'modelo': 'S7-1500', 'quantidade': 4},
        ],
    },
    {
        'id': INFRA_IDS['LAB_SVP_3'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Laboratório de Realidade Virtual e Aumentada',
        'name': 'VR/AR Lab',
        'descricao': 'Espaço para desenvolvimento de aplicações de realidade virtual e aumentada para treinamento industrial.',
        'email_laboratorio': 'lab.vrar@isisvp.senai.br',
        'email_responsavel': 'pedro.santos@isisvp.senai.br',
        'area_predial_m2': 150,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 4.0,
        'maturidade_laboratorial': 3.8,
        'plataformas_tecnologicas': ['Realidade Virtual', 'Realidade Aumentada', 'Unity3D'],
        'areas_conhecimento': ['Engenharia de Software', 'Design'],
        'equipamentos': [
            {'nome': 'Headset VR', 'marca': 'Meta', 'modelo': 'Quest Pro', 'quantidade': 10},
            {'nome': 'Óculos AR', 'marca': 'Microsoft', 'modelo': 'HoloLens 2', 'quantidade': 5},
        ],
    },
    {
        'id': INFRA_IDS['LAB_SVP_4'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Laboratório de Prototipagem Rápida',
        'name': 'Rapid Prototyping Lab',
        'descricao': 'Laboratório equipado com impressoras 3D industriais e equipamentos de usinagem CNC.',
        'email_laboratorio': 'lab.prototipagem@isisvp.senai.br',
        'email_responsavel': 'ana.rodrigues@isisvp.senai.br',
        'area_predial_m2': 200,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.3,
        'maturidade_laboratorial': 4.1,
        'plataformas_tecnologicas': ['Impressão 3D', 'CNC', 'CAM'],
        'areas_conhecimento': ['Engenharia Mecânica', 'Design de Produto'],
        'equipamentos': [
            {'nome': 'Impressora 3D Industrial', 'marca': 'Stratasys', 'modelo': 'F370', 'quantidade': 3},
            {'nome': 'Centro de Usinagem CNC', 'marca': 'Romi', 'modelo': 'D600', 'quantidade': 2},
        ],
    },
    {
        'id': INFRA_IDS['LAB_SVP_5'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Laboratório de Metrologia Digital',
        'name': 'Digital Metrology Lab',
        'descricao': 'Laboratório de metrologia com sistemas de medição 3D e controle dimensional automatizado.',
        'email_laboratorio': 'lab.metrologia@isisvp.senai.br',
        'email_responsavel': 'lucas.oliveira@isisvp.senai.br',
        'area_predial_m2': 120,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.4,
        'maturidade_laboratorial': 4.5,
        'plataformas_tecnologicas': ['Metrologia 3D', 'Digitalização', 'Controle Dimensional'],
        'areas_conhecimento': ['Engenharia de Produção', 'Qualidade'],
        'equipamentos': [
            {'nome': 'Scanner 3D', 'marca': 'GOM', 'modelo': 'ATOS Q', 'quantidade': 2},
            {'nome': 'Máquina de Medição por Coordenadas', 'marca': 'Zeiss', 'modelo': 'Contura', 'quantidade': 1},
        ],
    },
    # ISI QV Labs (5)
    {
        'id': INFRA_IDS['LAB_QV_1'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Laboratório de Química Analítica Verde',
        'name': 'Green Analytical Chemistry Lab',
        'descricao': 'Laboratório para análise e desenvolvimento de processos químicos sustentáveis.',
        'email_laboratorio': 'lab.analitica@isiqv.senai.br',
        'email_responsavel': 'roberto.almeida@isiqv.senai.br',
        'area_predial_m2': 300,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.6,
        'maturidade_laboratorial': 4.5,
        'plataformas_tecnologicas': ['Química Verde', 'Análise Instrumental'],
        'areas_conhecimento': ['Química', 'Engenharia Química'],
        'equipamentos': [
            {'nome': 'Cromatógrafo', 'marca': 'Agilent', 'modelo': '7890B GC', 'quantidade': 2},
            {'nome': 'Espectrômetro de Massas', 'marca': 'Thermo Fisher', 'modelo': 'Q Exactive', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_QV_2'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Laboratório de Biocombustíveis',
        'name': 'Biofuels Lab',
        'descricao': 'Planta piloto para desenvolvimento de biocombustíveis de segunda geração.',
        'email_laboratorio': 'lab.biocombustiveis@isiqv.senai.br',
        'email_responsavel': 'fernanda.lima@isiqv.senai.br',
        'area_predial_m2': 450,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.4,
        'maturidade_laboratorial': 4.3,
        'plataformas_tecnologicas': ['Biocombustíveis', 'Biotecnologia', 'Fermentação'],
        'areas_conhecimento': ['Engenharia Química', 'Biotecnologia'],
        'equipamentos': [
            {'nome': 'Reator de Bancada', 'marca': 'Parr', 'modelo': '4848', 'quantidade': 3},
            {'nome': 'Fermentador', 'marca': 'Sartorius', 'modelo': 'Biostat B', 'quantidade': 2},
        ],
    },
    {
        'id': INFRA_IDS['LAB_QV_3'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Laboratório de Catálise',
        'name': 'Catalysis Lab',
        'descricao': 'Laboratório especializado em desenvolvimento de catalisadores sustentáveis.',
        'email_laboratorio': 'lab.catalise@isiqv.senai.br',
        'email_responsavel': 'gustavo.martins@isiqv.senai.br',
        'area_predial_m2': 180,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 4.2,
        'maturidade_laboratorial': 4.0,
        'plataformas_tecnologicas': ['Catálise Heterogênea', 'Química Verde'],
        'areas_conhecimento': ['Química', 'Engenharia de Materiais'],
        'equipamentos': [
            {'nome': 'Analisador de Área Superficial', 'marca': 'Micromeritics', 'modelo': 'ASAP 2020', 'quantidade': 1},
            {'nome': 'Difratômetro de Raios-X', 'marca': 'Bruker', 'modelo': 'D8 Advance', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_QV_4'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Laboratório de Tratamento de Efluentes',
        'name': 'Effluent Treatment Lab',
        'descricao': 'Laboratório para desenvolvimento de tecnologias de tratamento de água e efluentes.',
        'email_laboratorio': 'lab.efluentes@isiqv.senai.br',
        'email_responsavel': 'camila.ferreira@isiqv.senai.br',
        'area_predial_m2': 220,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 4.0,
        'maturidade_laboratorial': 3.9,
        'plataformas_tecnologicas': ['Tratamento de Água', 'Sustentabilidade'],
        'areas_conhecimento': ['Engenharia Ambiental', 'Química'],
        'equipamentos': [
            {'nome': 'Sistema de Osmose Reversa', 'marca': 'Dow', 'modelo': 'FILMTEC', 'quantidade': 1},
            {'nome': 'Analisador de TOC', 'marca': 'Shimadzu', 'modelo': 'TOC-L', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_QV_5'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Laboratório de Síntese Orgânica',
        'name': 'Organic Synthesis Lab',
        'descricao': 'Laboratório para síntese de compostos orgânicos e desenvolvimento de rotas sintéticas.',
        'email_laboratorio': 'lab.sintese@isiqv.senai.br',
        'email_responsavel': 'bruno.pereira@isiqv.senai.br',
        'area_predial_m2': 160,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 4.1,
        'maturidade_laboratorial': 4.0,
        'plataformas_tecnologicas': ['Síntese Orgânica', 'Química Fina'],
        'areas_conhecimento': ['Química Orgânica'],
        'equipamentos': [
            {'nome': 'Reator de Fluxo Contínuo', 'marca': 'Vapourtec', 'modelo': 'RS-400', 'quantidade': 1},
            {'nome': 'Espectrômetro RMN', 'marca': 'Bruker', 'modelo': 'Avance III', 'quantidade': 1},
        ],
    },
    # ISI B&F Labs (5)
    {
        'id': INFRA_IDS['LAB_BF_1'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Laboratório de Fibras e Polímeros',
        'name': 'Fibers and Polymers Lab',
        'descricao': 'Laboratório para desenvolvimento de fibras têxteis e polímeros biossintéticos.',
        'email_laboratorio': 'lab.fibras@isibf.senai.br',
        'email_responsavel': 'patricia.souza@isibf.senai.br',
        'area_predial_m2': 280,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 4.0,
        'maturidade_laboratorial': 3.8,
        'plataformas_tecnologicas': ['Biossintéticos', 'Polímeros', 'Têxtil'],
        'areas_conhecimento': ['Engenharia de Materiais', 'Química'],
        'equipamentos': [
            {'nome': 'Extrusora de Polímeros', 'marca': 'Brabender', 'modelo': 'Plasti-Corder', 'quantidade': 1},
            {'nome': 'Máquina Universal de Ensaios', 'marca': 'Instron', 'modelo': '5982', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_BF_2'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Laboratório de Biotecnologia Têxtil',
        'name': 'Textile Biotechnology Lab',
        'descricao': 'Laboratório para processos biotecnológicos aplicados à indústria têxtil.',
        'email_laboratorio': 'lab.biotex@isibf.senai.br',
        'email_responsavel': 'ricardo.gomes@isibf.senai.br',
        'area_predial_m2': 200,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 3.9,
        'maturidade_laboratorial': 3.7,
        'plataformas_tecnologicas': ['Biotecnologia', 'Enzimologia', 'Têxtil'],
        'areas_conhecimento': ['Biotecnologia', 'Engenharia Têxtil'],
        'equipamentos': [
            {'nome': 'Fermentador', 'marca': 'New Brunswick', 'modelo': 'BioFlo 320', 'quantidade': 2},
            {'nome': 'Liofilizador', 'marca': 'Labconco', 'modelo': 'FreeZone', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_BF_3'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Laboratório de Caracterização de Materiais',
        'name': 'Materials Characterization Lab',
        'descricao': 'Laboratório para análise e caracterização de materiais poliméricos e fibras.',
        'email_laboratorio': 'lab.caracterizacao@isibf.senai.br',
        'email_responsavel': 'juliana.castro@isibf.senai.br',
        'area_predial_m2': 180,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.2,
        'maturidade_laboratorial': 4.0,
        'plataformas_tecnologicas': ['Análise Térmica', 'Microscopia'],
        'areas_conhecimento': ['Engenharia de Materiais'],
        'equipamentos': [
            {'nome': 'Microscópio Eletrônico', 'marca': 'JEOL', 'modelo': 'JSM-6510', 'quantidade': 1},
            {'nome': 'DSC', 'marca': 'TA Instruments', 'modelo': 'Q2000', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_BF_4'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Laboratório de Tingimento Sustentável',
        'name': 'Sustainable Dyeing Lab',
        'descricao': 'Laboratório para desenvolvimento de processos de tingimento eco-friendly.',
        'email_laboratorio': 'lab.tingimento@isibf.senai.br',
        'email_responsavel': 'thiago.ribeiro@isibf.senai.br',
        'area_predial_m2': 150,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 3.8,
        'maturidade_laboratorial': 3.6,
        'plataformas_tecnologicas': ['Tingimento', 'Sustentabilidade', 'Corantes Naturais'],
        'areas_conhecimento': ['Engenharia Têxtil', 'Química'],
        'equipamentos': [
            {'nome': 'Máquina de Tingimento', 'marca': 'Ahiba', 'modelo': 'Nuance ECO', 'quantidade': 2},
            {'nome': 'Espectrofotômetro', 'marca': 'Datacolor', 'modelo': '800', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_BF_5'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Laboratório de Fiação e Tecelagem',
        'name': 'Spinning and Weaving Lab',
        'descricao': 'Laboratório piloto para processos de fiação e tecelagem de fibras naturais.',
        'email_laboratorio': 'lab.fiacao@isibf.senai.br',
        'email_responsavel': 'larissa.mendes@isibf.senai.br',
        'area_predial_m2': 350,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 3.7,
        'maturidade_laboratorial': 3.5,
        'plataformas_tecnologicas': ['Fiação', 'Tecelagem', 'Acabamento'],
        'areas_conhecimento': ['Engenharia Têxtil'],
        'equipamentos': [
            {'nome': 'Filatório Piloto', 'marca': 'Rieter', 'modelo': 'R 66', 'quantidade': 1},
            {'nome': 'Tear de Amostras', 'marca': 'CCI', 'modelo': 'Sample Loom', 'quantidade': 2},
        ],
    },
    # ISI II Labs (5)
    {
        'id': INFRA_IDS['LAB_II_1'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Laboratório de Visão Computacional',
        'name': 'Computer Vision Lab',
        'descricao': 'Laboratório com sistemas de visão computacional e processamento de imagens.',
        'email_laboratorio': 'lab.visao@isiii.senai.br',
        'email_responsavel': 'andre.oliveira@isiii.senai.br',
        'area_predial_m2': 200,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.4,
        'maturidade_laboratorial': 4.2,
        'plataformas_tecnologicas': ['Visão Computacional', 'IA', 'Deep Learning'],
        'areas_conhecimento': ['Ciência da Computação', 'Engenharia Elétrica'],
        'equipamentos': [
            {'nome': 'Câmera Industrial', 'marca': 'Basler', 'modelo': 'acA4112-30um', 'quantidade': 8},
            {'nome': 'GPU Server', 'marca': 'NVIDIA', 'modelo': 'DGX A100', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_II_2'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Laboratório de Ensaios Não Destrutivos',
        'name': 'Non-Destructive Testing Lab',
        'descricao': 'Laboratório especializado em técnicas de END: ultrassom, radiografia.',
        'email_laboratorio': 'lab.end@isiii.senai.br',
        'email_responsavel': 'lucas.mendes@isiii.senai.br',
        'area_predial_m2': 350,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.3,
        'maturidade_laboratorial': 4.4,
        'plataformas_tecnologicas': ['END', 'Ultrassom', 'Radiografia Industrial'],
        'areas_conhecimento': ['Engenharia de Materiais', 'Engenharia Mecânica'],
        'equipamentos': [
            {'nome': 'Ultrassom Phased Array', 'marca': 'Olympus', 'modelo': 'OmniScan X3', 'quantidade': 2},
            {'nome': 'Equipamento de Raios-X', 'marca': 'GE', 'modelo': 'Isovolt 225', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_II_3'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Laboratório de Inteligência Artificial',
        'name': 'Artificial Intelligence Lab',
        'descricao': 'Laboratório para desenvolvimento de modelos de IA e machine learning.',
        'email_laboratorio': 'lab.ia@isiii.senai.br',
        'email_responsavel': 'beatriz.santos@isiii.senai.br',
        'area_predial_m2': 150,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 4.5,
        'maturidade_laboratorial': 4.3,
        'plataformas_tecnologicas': ['Machine Learning', 'Deep Learning', 'MLOps'],
        'areas_conhecimento': ['Ciência da Computação', 'Estatística'],
        'equipamentos': [
            {'nome': 'Cluster de GPU', 'marca': 'NVIDIA', 'modelo': 'HGX A100', 'quantidade': 1},
            {'nome': 'Storage NVMe', 'marca': 'Pure Storage', 'modelo': 'FlashBlade', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_II_4'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Laboratório de Robótica Móvel',
        'name': 'Mobile Robotics Lab',
        'descricao': 'Laboratório para desenvolvimento de robôs móveis autônomos e drones.',
        'email_laboratorio': 'lab.robotica@isiii.senai.br',
        'email_responsavel': 'rafael.dias@isiii.senai.br',
        'area_predial_m2': 300,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 4.1,
        'maturidade_laboratorial': 4.0,
        'plataformas_tecnologicas': ['Robótica', 'Drones', 'Navegação Autônoma'],
        'areas_conhecimento': ['Engenharia Mecatrônica', 'Ciência da Computação'],
        'equipamentos': [
            {'nome': 'Drone Industrial', 'marca': 'DJI', 'modelo': 'Matrice 300 RTK', 'quantidade': 3},
            {'nome': 'AGV', 'marca': 'MiR', 'modelo': 'MiR250', 'quantidade': 2},
        ],
    },
    {
        'id': INFRA_IDS['LAB_II_5'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Laboratório de Termografia e Vibração',
        'name': 'Thermography and Vibration Lab',
        'descricao': 'Laboratório para diagnóstico preditivo usando termografia e análise de vibração.',
        'email_laboratorio': 'lab.termo@isiii.senai.br',
        'email_responsavel': 'amanda.carvalho@isiii.senai.br',
        'area_predial_m2': 180,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 4.0,
        'maturidade_laboratorial': 3.9,
        'plataformas_tecnologicas': ['Termografia', 'Análise de Vibração', 'Manutenção Preditiva'],
        'areas_conhecimento': ['Engenharia Mecânica'],
        'equipamentos': [
            {'nome': 'Câmera Termográfica', 'marca': 'FLIR', 'modelo': 'T865', 'quantidade': 3},
            {'nome': 'Analisador de Vibração', 'marca': 'SKF', 'modelo': 'Microlog', 'quantidade': 2},
        ],
    },
    # CIS SO Labs (5)
    {
        'id': INFRA_IDS['LAB_SO_1'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Espaço de Inovação e Design Thinking',
        'name': 'Innovation and Design Thinking Space',
        'descricao': 'Espaço colaborativo para workshops de inovação e design thinking.',
        'email_laboratorio': 'espaco.inovacao@cisso.sesisenai.org.br',
        'email_responsavel': 'juliana.ferreira@cisso.sesisenai.org.br',
        'area_predial_m2': 180,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 3.5,
        'maturidade_laboratorial': 3.6,
        'plataformas_tecnologicas': ['Design Thinking', 'Gestão', 'Transformação Digital'],
        'areas_conhecimento': ['Administração', 'Design'],
        'equipamentos': [
            {'nome': 'Display Interativo', 'marca': 'Microsoft', 'modelo': 'Surface Hub 2S', 'quantidade': 2},
            {'nome': 'Impressora 3D', 'marca': 'Ultimaker', 'modelo': 'S5', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_SO_2'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Laboratório de Análise de Dados',
        'name': 'Data Analytics Lab',
        'descricao': 'Laboratório para análise de dados empresariais e business intelligence.',
        'email_laboratorio': 'lab.dados@cisso.sesisenai.org.br',
        'email_responsavel': 'marcos.silva@cisso.sesisenai.org.br',
        'area_predial_m2': 120,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 3.8,
        'maturidade_laboratorial': 3.7,
        'plataformas_tecnologicas': ['Business Intelligence', 'Data Science', 'Analytics'],
        'areas_conhecimento': ['Administração', 'Ciência de Dados'],
        'equipamentos': [
            {'nome': 'Servidor de Analytics', 'marca': 'Dell', 'modelo': 'PowerEdge R640', 'quantidade': 2},
            {'nome': 'Estação de Trabalho', 'marca': 'HP', 'modelo': 'Z4 G4', 'quantidade': 8},
        ],
    },
    {
        'id': INFRA_IDS['LAB_SO_3'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Sala de Simulação Empresarial',
        'name': 'Business Simulation Room',
        'descricao': 'Sala equipada para simulações de gestão e jogos empresariais.',
        'email_laboratorio': 'sala.simulacao@cisso.sesisenai.org.br',
        'email_responsavel': 'carolina.santos@cisso.sesisenai.org.br',
        'area_predial_m2': 100,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 3.4,
        'maturidade_laboratorial': 3.5,
        'plataformas_tecnologicas': ['Simulação', 'Gamificação', 'Treinamento'],
        'areas_conhecimento': ['Administração', 'Educação Corporativa'],
        'equipamentos': [
            {'nome': 'Projetor Interativo', 'marca': 'Epson', 'modelo': 'EB-1485Fi', 'quantidade': 2},
            {'nome': 'Sistema de Videoconferência', 'marca': 'Poly', 'modelo': 'Studio X50', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_SO_4'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Centro de Transformação Digital',
        'name': 'Digital Transformation Center',
        'descricao': 'Centro para apoio à transformação digital de empresas industriais.',
        'email_laboratorio': 'centro.digital@cisso.sesisenai.org.br',
        'email_responsavel': 'felipe.lima@cisso.sesisenai.org.br',
        'area_predial_m2': 200,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'A',
        'maturidade_base_tecnologica': 3.9,
        'maturidade_laboratorial': 3.8,
        'plataformas_tecnologicas': ['Transformação Digital', 'Indústria 4.0', 'IoT'],
        'areas_conhecimento': ['Gestão da Inovação', 'Tecnologia da Informação'],
        'equipamentos': [
            {'nome': 'Demonstrador IoT', 'marca': 'Siemens', 'modelo': 'MindSphere', 'quantidade': 1},
            {'nome': 'Painel Smart Factory', 'marca': 'Rockwell', 'modelo': 'FactoryTalk', 'quantidade': 1},
        ],
    },
    {
        'id': INFRA_IDS['LAB_SO_5'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Coworking de Startups',
        'name': 'Startup Coworking Space',
        'descricao': 'Espaço de coworking para startups industriais e empreendedores.',
        'email_laboratorio': 'coworking@cisso.sesisenai.org.br',
        'email_responsavel': 'gabriela.costa@cisso.sesisenai.org.br',
        'area_predial_m2': 250,
        'status_isi': 'Operacional',
        'maturidade_gestao': 'B',
        'maturidade_base_tecnologica': 3.3,
        'maturidade_laboratorial': 3.2,
        'plataformas_tecnologicas': ['Empreendedorismo', 'Startups', 'Networking'],
        'areas_conhecimento': ['Administração', 'Empreendedorismo'],
        'equipamentos': [
            {'nome': 'Estação Hot Desk', 'marca': 'Herman Miller', 'modelo': 'Aeron', 'quantidade': 20},
            {'nome': 'Sala de Reunião', 'marca': 'Steelcase', 'modelo': 'Media:scape', 'quantidade': 3},
        ],
    },
]


def _table_exists(conn, table: str) -> bool:
    r = conn.execute(text("SELECT to_regclass(:t)"), {"t": table}).scalar()
    return r is not None


def seed_for_tenant(conn, tenant_id: str) -> None:
    if not _table_exists(conn, "infrastructures"):
        print("Skipping infrastructures seed: table not present")
        return

    for infra in INFRASTRUCTURES:
        stmt = text("""
            INSERT INTO infrastructures (
                id, tenant_id, instituto_id, nome, name, descricao,
                email_laboratorio, email_responsavel, area_predial_m2,
                status_isi, maturidade_gestao, maturidade_base_tecnologica,
                maturidade_laboratorial, plataformas_tecnologicas,
                areas_conhecimento, equipamentos,
                created_at, updated_at
            )
            SELECT
                :id, :tenant_id, :instituto_id, :nome, :name, :descricao,
                :email_laboratorio, :email_responsavel, :area_predial_m2,
                :status_isi, :maturidade_gestao, :maturidade_base_tecnologica,
                :maturidade_laboratorial, CAST(:plataformas_tecnologicas AS jsonb),
                CAST(:areas_conhecimento AS jsonb), CAST(:equipamentos AS jsonb),
                now(), now()
            WHERE NOT EXISTS (
                SELECT 1 FROM infrastructures WHERE tenant_id = :tenant_id AND id = :id
            )
        """)
        
        conn.execute(stmt, {
            'id': infra['id'],
            'tenant_id': tenant_id,
            'instituto_id': infra['instituto_id'],
            'nome': infra['nome'],
            'name': infra['name'],
            'descricao': infra['descricao'],
            'email_laboratorio': infra['email_laboratorio'],
            'email_responsavel': infra['email_responsavel'],
            'area_predial_m2': infra['area_predial_m2'],
            'status_isi': infra['status_isi'],
            'maturidade_gestao': infra['maturidade_gestao'],
            'maturidade_base_tecnologica': infra['maturidade_base_tecnologica'],
            'maturidade_laboratorial': infra['maturidade_laboratorial'],
            'plataformas_tecnologicas': json.dumps(infra['plataformas_tecnologicas']),
            'areas_conhecimento': json.dumps(infra['areas_conhecimento']),
            'equipamentos': json.dumps(infra['equipamentos']),
        })

    print(f"infrastructures seed applied for tenant: {tenant_id}")


def seed_for_tenants(conn, tenant_ids: Iterable[str]) -> None:
    for t in tenant_ids:
        seed_for_tenant(conn, t)
