"""Seed Portfolio Projects (25 institutional R&D projects - 5 per institute)

This seed creates portfolio projects linked to each ISI/CIS institute.
These are detailed project records with company info, outcomes, and metrics.

Revision ID: portfolio_projects_seed
Create Date: 2026-01-24 12:00:00
"""
from __future__ import annotations

import json
from typing import Iterable
from sqlalchemy import text

# Inline stable IDs to avoid cross-module import issues in Docker
INSTITUTE_IDS = {
    'ISI_SVP': 'a1000000-0000-0000-0000-000000000001',
    'ISI_QV': 'a1000000-0000-0000-0000-000000000002',
    'ISI_BF': 'a1000000-0000-0000-0000-000000000003',
    'ISI_II': 'a1000000-0000-0000-0000-000000000004',
    'CIS_SO': 'a1000000-0000-0000-0000-000000000005',
}

TEAM_IDS = {
    'TEAM_SVP_1': 'b1000000-0000-0000-0000-000000000001',
    'TEAM_SVP_2': 'b1000000-0000-0000-0000-000000000002',
    'TEAM_SVP_3': 'b1000000-0000-0000-0000-000000000003',
    'TEAM_SVP_4': 'b1000000-0000-0000-0000-000000000004',
    'TEAM_SVP_5': 'b1000000-0000-0000-0000-000000000005',
    'TEAM_QV_1': 'b1000000-0000-0000-0000-000000000006',
    'TEAM_QV_2': 'b1000000-0000-0000-0000-000000000007',
    'TEAM_QV_3': 'b1000000-0000-0000-0000-000000000008',
    'TEAM_QV_4': 'b1000000-0000-0000-0000-000000000009',
    'TEAM_QV_5': 'b1000000-0000-0000-0000-000000000010',
    'TEAM_BF_1': 'b1000000-0000-0000-0000-000000000011',
    'TEAM_BF_2': 'b1000000-0000-0000-0000-000000000012',
    'TEAM_BF_3': 'b1000000-0000-0000-0000-000000000013',
    'TEAM_BF_4': 'b1000000-0000-0000-0000-000000000014',
    'TEAM_BF_5': 'b1000000-0000-0000-0000-000000000015',
    'TEAM_II_1': 'b1000000-0000-0000-0000-000000000016',
    'TEAM_II_2': 'b1000000-0000-0000-0000-000000000017',
    'TEAM_II_3': 'b1000000-0000-0000-0000-000000000018',
    'TEAM_II_4': 'b1000000-0000-0000-0000-000000000019',
    'TEAM_II_5': 'b1000000-0000-0000-0000-000000000020',
    'TEAM_SO_1': 'b1000000-0000-0000-0000-000000000021',
    'TEAM_SO_2': 'b1000000-0000-0000-0000-000000000022',
    'TEAM_SO_3': 'b1000000-0000-0000-0000-000000000023',
    'TEAM_SO_4': 'b1000000-0000-0000-0000-000000000024',
    'TEAM_SO_5': 'b1000000-0000-0000-0000-000000000025',
}

INFRA_IDS = {
    'LAB_SVP_1': 'c1000000-0000-0000-0000-000000000001',
    'LAB_SVP_2': 'c1000000-0000-0000-0000-000000000002',
    'LAB_SVP_3': 'c1000000-0000-0000-0000-000000000003',
    'LAB_SVP_4': 'c1000000-0000-0000-0000-000000000004',
    'LAB_SVP_5': 'c1000000-0000-0000-0000-000000000005',
    'LAB_QV_1': 'c1000000-0000-0000-0000-000000000006',
    'LAB_QV_2': 'c1000000-0000-0000-0000-000000000007',
    'LAB_QV_3': 'c1000000-0000-0000-0000-000000000008',
    'LAB_QV_4': 'c1000000-0000-0000-0000-000000000009',
    'LAB_QV_5': 'c1000000-0000-0000-0000-000000000010',
    'LAB_BF_1': 'c1000000-0000-0000-0000-000000000011',
    'LAB_BF_2': 'c1000000-0000-0000-0000-000000000012',
    'LAB_BF_3': 'c1000000-0000-0000-0000-000000000013',
    'LAB_BF_4': 'c1000000-0000-0000-0000-000000000014',
    'LAB_BF_5': 'c1000000-0000-0000-0000-000000000015',
    'LAB_II_1': 'c1000000-0000-0000-0000-000000000016',
    'LAB_II_2': 'c1000000-0000-0000-0000-000000000017',
    'LAB_II_3': 'c1000000-0000-0000-0000-000000000018',
    'LAB_II_4': 'c1000000-0000-0000-0000-000000000019',
    'LAB_II_5': 'c1000000-0000-0000-0000-000000000020',
    'LAB_SO_1': 'c1000000-0000-0000-0000-000000000021',
    'LAB_SO_2': 'c1000000-0000-0000-0000-000000000022',
    'LAB_SO_3': 'c1000000-0000-0000-0000-000000000023',
    'LAB_SO_4': 'c1000000-0000-0000-0000-000000000024',
    'LAB_SO_5': 'c1000000-0000-0000-0000-000000000025',
}


# Stable IDs for portfolio projects (25 total - 5 per institute)
PROJECT_IDS = {
    # ISI SVP Projects (5)
    'PROJ_SVP_1': 'd1000000-0000-0000-0000-000000000001',
    'PROJ_SVP_2': 'd1000000-0000-0000-0000-000000000002',
    'PROJ_SVP_3': 'd1000000-0000-0000-0000-000000000003',
    'PROJ_SVP_4': 'd1000000-0000-0000-0000-000000000004',
    'PROJ_SVP_5': 'd1000000-0000-0000-0000-000000000005',
    # ISI QV Projects (5)
    'PROJ_QV_1': 'd1000000-0000-0000-0000-000000000006',
    'PROJ_QV_2': 'd1000000-0000-0000-0000-000000000007',
    'PROJ_QV_3': 'd1000000-0000-0000-0000-000000000008',
    'PROJ_QV_4': 'd1000000-0000-0000-0000-000000000009',
    'PROJ_QV_5': 'd1000000-0000-0000-0000-000000000010',
    # ISI B&F Projects (5)
    'PROJ_BF_1': 'd1000000-0000-0000-0000-000000000011',
    'PROJ_BF_2': 'd1000000-0000-0000-0000-000000000012',
    'PROJ_BF_3': 'd1000000-0000-0000-0000-000000000013',
    'PROJ_BF_4': 'd1000000-0000-0000-0000-000000000014',
    'PROJ_BF_5': 'd1000000-0000-0000-0000-000000000015',
    # ISI II Projects (5)
    'PROJ_II_1': 'd1000000-0000-0000-0000-000000000016',
    'PROJ_II_2': 'd1000000-0000-0000-0000-000000000017',
    'PROJ_II_3': 'd1000000-0000-0000-0000-000000000018',
    'PROJ_II_4': 'd1000000-0000-0000-0000-000000000019',
    'PROJ_II_5': 'd1000000-0000-0000-0000-000000000020',
    # CIS SO Projects (5)
    'PROJ_SO_1': 'd1000000-0000-0000-0000-000000000021',
    'PROJ_SO_2': 'd1000000-0000-0000-0000-000000000022',
    'PROJ_SO_3': 'd1000000-0000-0000-0000-000000000023',
    'PROJ_SO_4': 'd1000000-0000-0000-0000-000000000024',
    'PROJ_SO_5': 'd1000000-0000-0000-0000-000000000025',
}

PORTFOLIO_PROJECTS = [
    # ========== ISI SVP Projects (5) ==========
    {
        'id': PROJECT_IDS['PROJ_SVP_1'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Gêmeo Digital para Linha de Montagem Automotiva',
        'descricao': 'Desenvolvimento de sistema de gêmeo digital para otimização de linha de montagem, reduzindo tempo de setup e aumentando eficiência produtiva.',
        'trl_entrada': 3,
        'trl_saida': 6,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'Lei de Informática',
        'edital_fomento': 'Chamada EMBRAPII 2025/01',
        'areas_conhecimento': ['Engenharia de Produção', 'Ciência da Computação'],
        'macroareas_pesquisa': ['Indústria 4.0', 'Manufatura Digital'],
        'plataformas_tecnologicas': ['Digital Twin', 'IoT', 'Simulação'],
        'tematicas': ['Automação', 'Otimização de Processos'],
        'parceiros': [{'nome': 'UFSC', 'tipo': 'ICT'}, {'nome': 'EMBRAPII', 'tipo': 'Fomento'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Volkswagen do Brasil',
        'empresa_atendida_cnpj': '59.104.422/0001-50',
        'empresa_atendida_cidade': 'São Bernardo do Campo',
        'empresa_atendida_uf': 'SP',
        'empresa_atendida_setor_cnae': 'C29.1',
        'empresa_atendida_depoimento': 'O projeto permitiu reduzir em 35% o tempo de setup da linha de montagem.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-03-01',
        'data_fim': '2025-09-30',
        'valor_total': 2500000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SVP_1'], TEAM_IDS['TEAM_SVP_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SVP_1'], INFRA_IDS['LAB_SVP_2']],
        'indicadores': {'reducao_tempo_setup': 35, 'aumento_produtividade': 18, 'roi_estimado': 2.5},
        'licoes_aprendidas': 'Integração com sistemas legados requer análise detalhada da arquitetura existente.',
    },
    {
        'id': PROJECT_IDS['PROJ_SVP_2'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Plataforma de Realidade Aumentada para Treinamento Industrial',
        'descricao': 'Desenvolvimento de plataforma de RA para capacitação de operadores em processos de manufatura complexos.',
        'trl_entrada': 2,
        'trl_saida': 5,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'FINEP',
        'edital_fomento': 'FINEP Inovação 2024',
        'areas_conhecimento': ['Engenharia de Software', 'Educação'],
        'macroareas_pesquisa': ['Indústria 4.0', 'Educação Profissional'],
        'plataformas_tecnologicas': ['Realidade Aumentada', 'Mobile'],
        'tematicas': ['Treinamento', 'Capacitação'],
        'parceiros': [{'nome': 'Microsoft', 'tipo': 'Empresa'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'WEG Equipamentos Elétricos',
        'empresa_atendida_cnpj': '84.429.695/0001-11',
        'empresa_atendida_cidade': 'Jaraguá do Sul',
        'empresa_atendida_uf': 'SC',
        'empresa_atendida_setor_cnae': 'C27.1',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-01-15',
        'data_fim': '2026-06-30',
        'valor_total': 1800000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SVP_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SVP_3']],
        'indicadores': {'operadores_treinados': 150, 'reducao_tempo_treinamento': 40},
    },
    {
        'id': PROJECT_IDS['PROJ_SVP_3'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Sistema de Manutenção Preditiva com IoT',
        'descricao': 'Plataforma IoT para coleta de dados de sensores e predição de falhas em equipamentos industriais usando machine learning.',
        'trl_entrada': 4,
        'trl_saida': 7,
        'categoria_solucao_resultante': 'Sistema',
        'modalidade_fomento': 'EMBRAPII',
        'edital_fomento': 'EMBRAPII IoT 2024',
        'areas_conhecimento': ['Engenharia Elétrica', 'Ciência da Computação'],
        'macroareas_pesquisa': ['IoT Industrial', 'Manutenção Preditiva'],
        'plataformas_tecnologicas': ['IoT', 'Machine Learning', 'Edge Computing'],
        'tematicas': ['Manutenção', 'Indústria 4.0'],
        'parceiros': [{'nome': 'Siemens', 'tipo': 'Empresa'}, {'nome': 'UNICAMP', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Gerdau S.A.',
        'empresa_atendida_cnpj': '33.611.500/0001-19',
        'empresa_atendida_cidade': 'Porto Alegre',
        'empresa_atendida_uf': 'RS',
        'empresa_atendida_setor_cnae': 'C24.2',
        'empresa_atendida_depoimento': 'Reduzimos paradas não programadas em 60% após implementação.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2023-07-01',
        'data_fim': '2025-06-30',
        'valor_total': 3200000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SVP_1'], TEAM_IDS['TEAM_SVP_3']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SVP_2'], INFRA_IDS['LAB_SVP_5']],
        'indicadores': {'reducao_paradas': 60, 'sensores_instalados': 500, 'acuracia_predicao': 92},
        'licoes_aprendidas': 'Qualidade dos dados é fundamental para modelos preditivos confiáveis.',
    },
    {
        'id': PROJECT_IDS['PROJ_SVP_4'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Robô Colaborativo para Montagem de Componentes Eletrônicos',
        'descricao': 'Desenvolvimento de célula robótica colaborativa para montagem de placas eletrônicas com alta precisão.',
        'trl_entrada': 3,
        'trl_saida': 6,
        'categoria_solucao_resultante': 'Sistema',
        'modalidade_fomento': 'Lei de Informática',
        'edital_fomento': 'Lei 8.248 - 2025',
        'areas_conhecimento': ['Engenharia Mecatrônica', 'Robótica'],
        'macroareas_pesquisa': ['Robótica', 'Automação'],
        'plataformas_tecnologicas': ['Robótica Colaborativa', 'Visão Computacional'],
        'tematicas': ['Automação', 'Manufatura'],
        'parceiros': [{'nome': 'KUKA', 'tipo': 'Empresa'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Samsung Electronics',
        'empresa_atendida_cnpj': '00.280.273/0001-37',
        'empresa_atendida_cidade': 'Manaus',
        'empresa_atendida_uf': 'AM',
        'empresa_atendida_setor_cnae': 'C26.2',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-02-01',
        'data_fim': '2026-08-31',
        'valor_total': 2100000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SVP_4']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SVP_2'], INFRA_IDS['LAB_SVP_4']],
        'indicadores': {'precisao_posicionamento_mm': 0.05, 'ciclos_por_minuto': 12},
    },
    {
        'id': PROJECT_IDS['PROJ_SVP_5'],
        'instituto_id': INSTITUTE_IDS['ISI_SVP'],
        'nome': 'Otimização de Layout Industrial via Simulação Discreta',
        'descricao': 'Ferramenta de simulação para otimização de layouts industriais e fluxo de materiais.',
        'trl_entrada': 5,
        'trl_saida': 8,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'SEBRAE',
        'edital_fomento': 'Sebraetec 2025',
        'areas_conhecimento': ['Engenharia de Produção'],
        'macroareas_pesquisa': ['Simulação', 'Logística'],
        'plataformas_tecnologicas': ['Simulação Discreta', 'Otimização'],
        'tematicas': ['Layout Industrial', 'Produtividade'],
        'parceiros': [{'nome': 'SEBRAE-SP', 'tipo': 'Fomento'}],
        'empresa_atendida_tipo': 'Média',
        'empresa_atendida_nome': 'Metalúrgica Riosulense',
        'empresa_atendida_cnpj': '83.210.929/0001-01',
        'empresa_atendida_cidade': 'Rio do Sul',
        'empresa_atendida_uf': 'SC',
        'empresa_atendida_setor_cnae': 'C25.4',
        'empresa_atendida_depoimento': 'Aumentamos a produtividade em 25% com o novo layout proposto.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-08-01',
        'data_fim': '2025-04-30',
        'valor_total': 380000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SVP_5']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SVP_1']],
        'indicadores': {'aumento_produtividade': 25, 'reducao_movimentacao': 40},
        'licoes_aprendidas': 'Envolvimento do chão de fábrica é essencial para validação do layout.',
    },
    # ========== ISI QV Projects (5) ==========
    {
        'id': PROJECT_IDS['PROJ_QV_1'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Biocombustível de Segunda Geração a partir de Resíduos Agrícolas',
        'descricao': 'Pesquisa e desenvolvimento de processo para produção de etanol 2G utilizando resíduos da cana-de-açúcar.',
        'trl_entrada': 4,
        'trl_saida': 7,
        'categoria_solucao_resultante': 'Processo',
        'modalidade_fomento': 'BNDES',
        'edital_fomento': 'BNDES Fundo Clima',
        'areas_conhecimento': ['Química', 'Engenharia Química'],
        'macroareas_pesquisa': ['Energia Renovável', 'Sustentabilidade'],
        'plataformas_tecnologicas': ['Biotecnologia', 'Química Verde'],
        'tematicas': ['Biocombustíveis', 'Economia Circular'],
        'parceiros': [{'nome': 'Petrobras', 'tipo': 'Empresa'}, {'nome': 'UFRJ', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Raízen S.A.',
        'empresa_atendida_cnpj': '33.453.598/0001-23',
        'empresa_atendida_cidade': 'São Paulo',
        'empresa_atendida_uf': 'SP',
        'empresa_atendida_setor_cnae': 'C19.3',
        'empresa_atendida_depoimento': 'O processo desenvolvido viabiliza a utilização de 100% dos resíduos agrícolas.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2023-06-01',
        'data_fim': '2025-12-31',
        'valor_total': 4200000.00,
        'equipe_ids': [TEAM_IDS['TEAM_QV_1'], TEAM_IDS['TEAM_QV_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_QV_1'], INFRA_IDS['LAB_QV_2']],
        'indicadores': {'rendimento_processo': 85, 'reducao_emissoes_co2': 60, 'patentes_depositadas': 2},
        'licoes_aprendidas': 'Scale-up de processos biotecnológicos requer validação extensiva em planta piloto.',
    },
    {
        'id': PROJECT_IDS['PROJ_QV_2'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Catalisadores Heterogêneos para Hidrogenação de CO2',
        'descricao': 'Desenvolvimento de catalisadores para conversão de CO2 em metanol utilizando hidrogênio verde.',
        'trl_entrada': 2,
        'trl_saida': 5,
        'categoria_solucao_resultante': 'Processo',
        'modalidade_fomento': 'FAPESP',
        'edital_fomento': 'FAPESP PIPE Fase 2',
        'areas_conhecimento': ['Química', 'Engenharia de Materiais'],
        'macroareas_pesquisa': ['Captura de Carbono', 'Catálise'],
        'plataformas_tecnologicas': ['Catálise Heterogênea', 'Química Verde'],
        'tematicas': ['Descarbonização', 'Sustentabilidade'],
        'parceiros': [{'nome': 'USP', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Braskem S.A.',
        'empresa_atendida_cnpj': '42.150.391/0001-70',
        'empresa_atendida_cidade': 'Camaçari',
        'empresa_atendida_uf': 'BA',
        'empresa_atendida_setor_cnae': 'C20.2',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-01-01',
        'data_fim': '2027-06-30',
        'valor_total': 2800000.00,
        'equipe_ids': [TEAM_IDS['TEAM_QV_3']],
        'infraestrutura_ids': [INFRA_IDS['LAB_QV_3']],
        'indicadores': {'conversao_co2': 45, 'seletividade_metanol': 78},
    },
    {
        'id': PROJECT_IDS['PROJ_QV_3'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Sistema Avançado de Tratamento de Efluentes Petroquímicos',
        'descricao': 'Desenvolvimento de sistema integrado de tratamento de efluentes usando processos oxidativos avançados.',
        'trl_entrada': 4,
        'trl_saida': 7,
        'categoria_solucao_resultante': 'Sistema',
        'modalidade_fomento': 'ANP P&D',
        'edital_fomento': 'ANP P&D 2024',
        'areas_conhecimento': ['Engenharia Ambiental', 'Química'],
        'macroareas_pesquisa': ['Tratamento de Água', 'Meio Ambiente'],
        'plataformas_tecnologicas': ['POA', 'Membranas'],
        'tematicas': ['Sustentabilidade', 'Gestão Ambiental'],
        'parceiros': [{'nome': 'PETROBRAS', 'tipo': 'Empresa'}, {'nome': 'UFBA', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Petrobras',
        'empresa_atendida_cnpj': '33.000.167/0001-01',
        'empresa_atendida_cidade': 'Rio de Janeiro',
        'empresa_atendida_uf': 'RJ',
        'empresa_atendida_setor_cnae': 'B06.0',
        'empresa_atendida_depoimento': 'O sistema reduziu em 95% a DQO dos efluentes tratados.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2023-03-01',
        'data_fim': '2025-02-28',
        'valor_total': 3600000.00,
        'equipe_ids': [TEAM_IDS['TEAM_QV_4']],
        'infraestrutura_ids': [INFRA_IDS['LAB_QV_4']],
        'indicadores': {'reducao_dqo': 95, 'recuperacao_agua': 80},
        'licoes_aprendidas': 'Integração de múltiplas tecnologias é chave para tratamento eficiente.',
    },
    {
        'id': PROJECT_IDS['PROJ_QV_4'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Síntese de Intermediários Farmacêuticos por Química de Fluxo',
        'descricao': 'Desenvolvimento de rotas sintéticas contínuas para produção de intermediários farmacêuticos.',
        'trl_entrada': 3,
        'trl_saida': 6,
        'categoria_solucao_resultante': 'Processo',
        'modalidade_fomento': 'CNPq',
        'edital_fomento': 'CNPq Universal 2024',
        'areas_conhecimento': ['Química Orgânica', 'Engenharia Química'],
        'macroareas_pesquisa': ['Química Fina', 'Farmoquímicos'],
        'plataformas_tecnologicas': ['Química de Fluxo', 'Síntese Orgânica'],
        'tematicas': ['Saúde', 'Química Fina'],
        'parceiros': [{'nome': 'Farmanguinhos', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Eurofarma Laboratórios',
        'empresa_atendida_cnpj': '61.190.096/0001-92',
        'empresa_atendida_cidade': 'Ribeirão Preto',
        'empresa_atendida_uf': 'SP',
        'empresa_atendida_setor_cnae': 'C21.2',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-09-01',
        'data_fim': '2026-08-31',
        'valor_total': 1900000.00,
        'equipe_ids': [TEAM_IDS['TEAM_QV_5']],
        'infraestrutura_ids': [INFRA_IDS['LAB_QV_5']],
        'indicadores': {'rendimento_sintetico': 88, 'reducao_residuos': 65},
    },
    {
        'id': PROJECT_IDS['PROJ_QV_5'],
        'instituto_id': INSTITUTE_IDS['ISI_QV'],
        'nome': 'Polímeros Biodegradáveis de Origem Renovável',
        'descricao': 'Desenvolvimento de polímeros biodegradáveis a partir de fontes renováveis para embalagens.',
        'trl_entrada': 3,
        'trl_saida': 6,
        'categoria_solucao_resultante': 'Produto',
        'modalidade_fomento': 'EMBRAPII',
        'edital_fomento': 'EMBRAPII Sustentabilidade 2025',
        'areas_conhecimento': ['Engenharia de Materiais', 'Química'],
        'macroareas_pesquisa': ['Materiais Sustentáveis', 'Economia Circular'],
        'plataformas_tecnologicas': ['Biopolímeros', 'Processamento'],
        'tematicas': ['Sustentabilidade', 'Embalagens'],
        'parceiros': [{'nome': 'UNICAMP', 'tipo': 'ICT'}, {'nome': 'ABRE', 'tipo': 'Associação'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Natura Cosméticos',
        'empresa_atendida_cnpj': '71.673.990/0001-77',
        'empresa_atendida_cidade': 'Cajamar',
        'empresa_atendida_uf': 'SP',
        'empresa_atendida_setor_cnae': 'C20.6',
        'empresa_atendida_depoimento': 'Substituímos 100% das embalagens por materiais biodegradáveis.',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-03-01',
        'data_fim': '2027-02-28',
        'valor_total': 2400000.00,
        'equipe_ids': [TEAM_IDS['TEAM_QV_1'], TEAM_IDS['TEAM_QV_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_QV_1'], INFRA_IDS['LAB_QV_3']],
        'indicadores': {'biodegradabilidade_dias': 180, 'resistencia_mecanica_mpa': 35},
    },
    # ========== ISI B&F Projects (5) ==========
    {
        'id': PROJECT_IDS['PROJ_BF_1'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Fibras Têxteis Biodegradáveis de Alto Desempenho',
        'descricao': 'Desenvolvimento de fibras têxteis 100% biodegradáveis com propriedades mecânicas comparáveis a sintéticos.',
        'trl_entrada': 2,
        'trl_saida': 5,
        'categoria_solucao_resultante': 'Produto',
        'modalidade_fomento': 'CNPq',
        'edital_fomento': 'CNPq Universal 2024',
        'areas_conhecimento': ['Engenharia de Materiais', 'Química'],
        'macroareas_pesquisa': ['Materiais Avançados', 'Sustentabilidade'],
        'plataformas_tecnologicas': ['Biossintéticos', 'Têxtil'],
        'tematicas': ['Moda Sustentável', 'Economia Circular'],
        'parceiros': [{'nome': 'ABIT', 'tipo': 'Associação'}],
        'empresa_atendida_tipo': 'Média',
        'empresa_atendida_nome': 'Malwee Malhas Ltda',
        'empresa_atendida_cnpj': '84.429.628/0001-25',
        'empresa_atendida_cidade': 'Jaraguá do Sul',
        'empresa_atendida_uf': 'SC',
        'empresa_atendida_setor_cnae': 'C14.1',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-02-01',
        'data_fim': '2027-01-31',
        'valor_total': 1200000.00,
        'equipe_ids': [TEAM_IDS['TEAM_BF_1']],
        'infraestrutura_ids': [INFRA_IDS['LAB_BF_1']],
        'indicadores': {'biodegradabilidade': 95, 'resistencia_tracao_mpa': 450},
    },
    {
        'id': PROJECT_IDS['PROJ_BF_2'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Tingimento Enzimático de Tecidos de Algodão',
        'descricao': 'Desenvolvimento de processo de tingimento utilizando enzimas, reduzindo consumo de água e químicos.',
        'trl_entrada': 3,
        'trl_saida': 6,
        'categoria_solucao_resultante': 'Processo',
        'modalidade_fomento': 'FAPESP',
        'edital_fomento': 'FAPESP PIPE Fase 1',
        'areas_conhecimento': ['Biotecnologia', 'Engenharia Têxtil'],
        'macroareas_pesquisa': ['Biotecnologia', 'Sustentabilidade'],
        'plataformas_tecnologicas': ['Enzimologia', 'Tingimento'],
        'tematicas': ['Sustentabilidade', 'Processos Limpos'],
        'parceiros': [{'nome': 'CETIQT', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Média',
        'empresa_atendida_nome': 'Karsten S.A.',
        'empresa_atendida_cnpj': '82.640.558/0001-04',
        'empresa_atendida_cidade': 'Blumenau',
        'empresa_atendida_uf': 'SC',
        'empresa_atendida_setor_cnae': 'C13.5',
        'empresa_atendida_depoimento': 'Reduzimos em 70% o consumo de água no processo de tingimento.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2023-09-01',
        'data_fim': '2025-08-31',
        'valor_total': 890000.00,
        'equipe_ids': [TEAM_IDS['TEAM_BF_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_BF_2'], INFRA_IDS['LAB_BF_4']],
        'indicadores': {'reducao_agua': 70, 'reducao_quimicos': 80},
        'licoes_aprendidas': 'Seleção correta de enzimas é crítica para reprodutibilidade de cores.',
    },
    {
        'id': PROJECT_IDS['PROJ_BF_3'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Caracterização Avançada de Materiais Têxteis Reciclados',
        'descricao': 'Desenvolvimento de metodologias para caracterização de fibras têxteis pós-consumo visando reciclagem.',
        'trl_entrada': 4,
        'trl_saida': 7,
        'categoria_solucao_resultante': 'Metodologia',
        'modalidade_fomento': 'SENAI SESI Inovação',
        'edital_fomento': 'Edital Inovação 2024',
        'areas_conhecimento': ['Engenharia de Materiais'],
        'macroareas_pesquisa': ['Economia Circular', 'Reciclagem'],
        'plataformas_tecnologicas': ['Análise Térmica', 'Microscopia'],
        'tematicas': ['Reciclagem', 'Sustentabilidade'],
        'parceiros': [{'nome': 'Abvtex', 'tipo': 'Associação'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Renner S.A.',
        'empresa_atendida_cnpj': '92.754.738/0001-62',
        'empresa_atendida_cidade': 'Porto Alegre',
        'empresa_atendida_uf': 'RS',
        'empresa_atendida_setor_cnae': 'G47.8',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-11-01',
        'data_fim': '2026-04-30',
        'valor_total': 650000.00,
        'equipe_ids': [TEAM_IDS['TEAM_BF_3']],
        'infraestrutura_ids': [INFRA_IDS['LAB_BF_3']],
        'indicadores': {'tipos_fibras_identificaveis': 15, 'precisao_identificacao': 97},
    },
    {
        'id': PROJECT_IDS['PROJ_BF_4'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Corantes Naturais Estáveis para Indústria Têxtil',
        'descricao': 'Extração e estabilização de corantes naturais de plantas nativas para aplicação têxtil.',
        'trl_entrada': 2,
        'trl_saida': 5,
        'categoria_solucao_resultante': 'Produto',
        'modalidade_fomento': 'CNPq',
        'edital_fomento': 'CNPq Biodiversidade 2024',
        'areas_conhecimento': ['Química', 'Biotecnologia'],
        'macroareas_pesquisa': ['Produtos Naturais', 'Sustentabilidade'],
        'plataformas_tecnologicas': ['Corantes Naturais', 'Biotecnologia'],
        'tematicas': ['Moda Sustentável', 'Biodiversidade'],
        'parceiros': [{'nome': 'INPA', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Pequena',
        'empresa_atendida_nome': 'Ecomalhas Ltda',
        'empresa_atendida_cnpj': '12.345.678/0001-90',
        'empresa_atendida_cidade': 'Brusque',
        'empresa_atendida_uf': 'SC',
        'empresa_atendida_setor_cnae': 'C14.1',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-04-01',
        'data_fim': '2027-03-31',
        'valor_total': 720000.00,
        'equipe_ids': [TEAM_IDS['TEAM_BF_4']],
        'infraestrutura_ids': [INFRA_IDS['LAB_BF_4']],
        'indicadores': {'especies_estudadas': 12, 'solidez_lavagem': 4.5},
    },
    {
        'id': PROJECT_IDS['PROJ_BF_5'],
        'instituto_id': INSTITUTE_IDS['ISI_BF'],
        'nome': 'Otimização de Processos de Fiação para Fibras Naturais',
        'descricao': 'Desenvolvimento de parâmetros otimizados de fiação para fibras de algodão orgânico.',
        'trl_entrada': 5,
        'trl_saida': 8,
        'categoria_solucao_resultante': 'Processo',
        'modalidade_fomento': 'SEBRAE',
        'edital_fomento': 'Sebraetec 2024',
        'areas_conhecimento': ['Engenharia Têxtil'],
        'macroareas_pesquisa': ['Processos Têxteis', 'Produtividade'],
        'plataformas_tecnologicas': ['Fiação', 'Automação'],
        'tematicas': ['Produtividade', 'Qualidade'],
        'parceiros': [{'nome': 'SENAI-CETIQT', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Média',
        'empresa_atendida_nome': 'Fiação São Bento',
        'empresa_atendida_cnpj': '01.234.567/0001-89',
        'empresa_atendida_cidade': 'São Bento do Sul',
        'empresa_atendida_uf': 'SC',
        'empresa_atendida_setor_cnae': 'C13.1',
        'empresa_atendida_depoimento': 'A otimização aumentou nossa produtividade em 30%.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-03-01',
        'data_fim': '2025-02-28',
        'valor_total': 420000.00,
        'equipe_ids': [TEAM_IDS['TEAM_BF_5']],
        'infraestrutura_ids': [INFRA_IDS['LAB_BF_5']],
        'indicadores': {'aumento_produtividade': 30, 'reducao_perdas': 25},
        'licoes_aprendidas': 'Ajuste fino de parâmetros requer monitoramento contínuo da qualidade.',
    },
    # ========== ISI II Projects (5) ==========
    {
        'id': PROJECT_IDS['PROJ_II_1'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Sistema de Inspeção por Visão Computacional para Soldas',
        'descricao': 'Desenvolvimento de sistema automatizado de inspeção de soldas utilizando deep learning e visão computacional.',
        'trl_entrada': 3,
        'trl_saida': 7,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'EMBRAPII',
        'edital_fomento': 'Chamada EMBRAPII IA 2024',
        'areas_conhecimento': ['Ciência da Computação', 'Engenharia Mecânica'],
        'macroareas_pesquisa': ['Inteligência Artificial', 'Qualidade'],
        'plataformas_tecnologicas': ['Deep Learning', 'Visão Computacional'],
        'tematicas': ['Inspeção Automatizada', 'Controle de Qualidade'],
        'parceiros': [{'nome': 'USP', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Petrobras',
        'empresa_atendida_cnpj': '33.000.167/0001-01',
        'empresa_atendida_cidade': 'Rio de Janeiro',
        'empresa_atendida_uf': 'RJ',
        'empresa_atendida_setor_cnae': 'B06.0',
        'empresa_atendida_depoimento': 'Reduzimos em 70% o tempo de inspeção com maior precisão.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-01-01',
        'data_fim': '2025-06-30',
        'valor_total': 3100000.00,
        'equipe_ids': [TEAM_IDS['TEAM_II_1'], TEAM_IDS['TEAM_II_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_II_1'], INFRA_IDS['LAB_II_2']],
        'indicadores': {'acuracia_deteccao': 98.5, 'reducao_tempo_inspecao': 70, 'falsos_positivos': 1.2},
        'licoes_aprendidas': 'Dataset balanceado é crítico para performance do modelo de deep learning.',
    },
    {
        'id': PROJECT_IDS['PROJ_II_2'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Drone Autônomo para Inspeção de Linhas de Transmissão',
        'descricao': 'Desenvolvimento de drone com sistema de visão para inspeção automatizada de linhas de transmissão elétrica.',
        'trl_entrada': 4,
        'trl_saida': 6,
        'categoria_solucao_resultante': 'Sistema',
        'modalidade_fomento': 'ANEEL P&D',
        'edital_fomento': 'ANEEL P&D 2024',
        'areas_conhecimento': ['Engenharia Elétrica', 'Robótica'],
        'macroareas_pesquisa': ['Energia', 'Robótica'],
        'plataformas_tecnologicas': ['Drones', 'Visão Computacional', 'Navegação Autônoma'],
        'tematicas': ['Inspeção Remota', 'Manutenção Preditiva'],
        'parceiros': [{'nome': 'ITA', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'CPFL Energia',
        'empresa_atendida_cnpj': '02.429.144/0001-93',
        'empresa_atendida_cidade': 'Campinas',
        'empresa_atendida_uf': 'SP',
        'empresa_atendida_setor_cnae': 'D35.1',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-03-01',
        'data_fim': '2026-12-31',
        'valor_total': 2800000.00,
        'equipe_ids': [TEAM_IDS['TEAM_II_4']],
        'infraestrutura_ids': [INFRA_IDS['LAB_II_4']],
        'indicadores': {'autonomia_voo_min': 45, 'precisao_localizacao_cm': 10},
    },
    {
        'id': PROJECT_IDS['PROJ_II_3'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Plataforma de IA para Análise de Vibrações em Rotativas',
        'descricao': 'Sistema de machine learning para diagnóstico de falhas em máquinas rotativas baseado em análise de vibração.',
        'trl_entrada': 3,
        'trl_saida': 6,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'EMBRAPII',
        'edital_fomento': 'EMBRAPII Manutenção 2024',
        'areas_conhecimento': ['Engenharia Mecânica', 'Ciência da Computação'],
        'macroareas_pesquisa': ['Manutenção Preditiva', 'IA Industrial'],
        'plataformas_tecnologicas': ['Machine Learning', 'Análise de Vibração'],
        'tematicas': ['Manutenção', 'Confiabilidade'],
        'parceiros': [{'nome': 'SKF', 'tipo': 'Empresa'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Vale S.A.',
        'empresa_atendida_cnpj': '33.592.510/0001-54',
        'empresa_atendida_cidade': 'Rio de Janeiro',
        'empresa_atendida_uf': 'RJ',
        'empresa_atendida_setor_cnae': 'B07.1',
        'empresa_atendida_depoimento': 'O sistema antecipa falhas com até 30 dias de antecedência.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2023-10-01',
        'data_fim': '2025-09-30',
        'valor_total': 2200000.00,
        'equipe_ids': [TEAM_IDS['TEAM_II_5']],
        'infraestrutura_ids': [INFRA_IDS['LAB_II_5']],
        'indicadores': {'antecedencia_predicao_dias': 30, 'acuracia': 94},
        'licoes_aprendidas': 'Dados de operação normal são tão importantes quanto dados de falha.',
    },
    {
        'id': PROJECT_IDS['PROJ_II_4'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Sistema de Classificação de Defeitos por Ultrassom Phased Array',
        'descricao': 'Algoritmos de IA para classificação automática de descontinuidades detectadas por PAUT.',
        'trl_entrada': 4,
        'trl_saida': 7,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'ANP P&D',
        'edital_fomento': 'ANP P&D 2025',
        'areas_conhecimento': ['Engenharia de Materiais', 'Ciência da Computação'],
        'macroareas_pesquisa': ['END', 'Inteligência Artificial'],
        'plataformas_tecnologicas': ['Ultrassom', 'Deep Learning'],
        'tematicas': ['Inspeção', 'Qualidade'],
        'parceiros': [{'nome': 'Olympus', 'tipo': 'Empresa'}, {'nome': 'UFRJ', 'tipo': 'ICT'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Transpetro',
        'empresa_atendida_cnpj': '02.709.449/0001-59',
        'empresa_atendida_cidade': 'Rio de Janeiro',
        'empresa_atendida_uf': 'RJ',
        'empresa_atendida_setor_cnae': 'H49.5',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-01-15',
        'data_fim': '2026-07-31',
        'valor_total': 1850000.00,
        'equipe_ids': [TEAM_IDS['TEAM_II_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_II_2']],
        'indicadores': {'tipos_defeitos': 8, 'acuracia_classificacao': 96},
    },
    {
        'id': PROJECT_IDS['PROJ_II_5'],
        'instituto_id': INSTITUTE_IDS['ISI_II'],
        'nome': 'Gêmeo Digital para Simulação de Processos de Inspeção',
        'descricao': 'Modelagem digital de processos de inspeção industrial para otimização de procedimentos.',
        'trl_entrada': 2,
        'trl_saida': 5,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'FINEP',
        'edital_fomento': 'FINEP Industria 4.0 2024',
        'areas_conhecimento': ['Engenharia de Produção', 'Ciência da Computação'],
        'macroareas_pesquisa': ['Digital Twin', 'Simulação'],
        'plataformas_tecnologicas': ['Digital Twin', 'Simulação'],
        'tematicas': ['Indústria 4.0', 'Otimização'],
        'parceiros': [{'nome': 'Dassault Systèmes', 'tipo': 'Empresa'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Embraer S.A.',
        'empresa_atendida_cnpj': '07.689.002/0001-89',
        'empresa_atendida_cidade': 'São José dos Campos',
        'empresa_atendida_uf': 'SP',
        'empresa_atendida_setor_cnae': 'C30.4',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-06-01',
        'data_fim': '2027-05-31',
        'valor_total': 3400000.00,
        'equipe_ids': [TEAM_IDS['TEAM_II_1'], TEAM_IDS['TEAM_II_3']],
        'infraestrutura_ids': [INFRA_IDS['LAB_II_1'], INFRA_IDS['LAB_II_3']],
        'indicadores': {'processos_modelados': 15, 'reducao_retrabalho': 40},
    },
    # ========== CIS SO Projects (5) ==========
    {
        'id': PROJECT_IDS['PROJ_SO_1'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Transformação Digital para PMEs Industriais',
        'descricao': 'Metodologia e ferramentas para acelerar a transformação digital de pequenas e médias empresas do setor industrial.',
        'trl_entrada': 5,
        'trl_saida': 8,
        'categoria_solucao_resultante': 'Metodologia',
        'modalidade_fomento': 'SEBRAE',
        'edital_fomento': 'Programa ALI 2024',
        'areas_conhecimento': ['Administração', 'Tecnologia da Informação'],
        'macroareas_pesquisa': ['Gestão', 'Transformação Digital'],
        'plataformas_tecnologicas': ['Cloud', 'Gestão'],
        'tematicas': ['Competitividade', 'Inovação Organizacional'],
        'parceiros': [{'nome': 'SEBRAE-PR', 'tipo': 'Fomento'}],
        'empresa_atendida_tipo': 'Pequena',
        'empresa_atendida_nome': 'Metalúrgica Precision Ltda',
        'empresa_atendida_cnpj': '78.123.456/0001-00',
        'empresa_atendida_cidade': 'Curitiba',
        'empresa_atendida_uf': 'PR',
        'empresa_atendida_setor_cnae': 'C25.1',
        'empresa_atendida_depoimento': 'A metodologia nos permitiu digitalizar processos críticos em 6 meses.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-06-01',
        'data_fim': '2025-05-31',
        'valor_total': 450000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SO_1']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SO_1']],
        'indicadores': {'empresas_atendidas': 25, 'aumento_produtividade_medio': 22, 'nps': 92},
        'licoes_aprendidas': 'Engajamento da liderança é fator crítico de sucesso na transformação digital.',
    },
    {
        'id': PROJECT_IDS['PROJ_SO_2'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Diagnóstico de Maturidade Digital Industrial',
        'descricao': 'Ferramenta de avaliação do nível de maturidade digital de empresas industriais.',
        'trl_entrada': 6,
        'trl_saida': 9,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'SENAI',
        'edital_fomento': 'Programa SENAI 4.0',
        'areas_conhecimento': ['Administração', 'Tecnologia da Informação'],
        'macroareas_pesquisa': ['Indústria 4.0', 'Gestão'],
        'plataformas_tecnologicas': ['Web', 'Analytics'],
        'tematicas': ['Diagnóstico', 'Maturidade Digital'],
        'parceiros': [{'nome': 'CNI', 'tipo': 'Associação'}],
        'empresa_atendida_tipo': 'Diversas',
        'empresa_atendida_nome': 'Programa Multi-empresas',
        'empresa_atendida_cnpj': '',
        'empresa_atendida_cidade': 'Porto Alegre',
        'empresa_atendida_uf': 'RS',
        'empresa_atendida_setor_cnae': 'C - Geral',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2023-08-01',
        'data_fim': '2024-12-31',
        'valor_total': 380000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SO_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SO_2']],
        'indicadores': {'empresas_diagnosticadas': 150, 'satisfacao': 95},
        'licoes_aprendidas': 'Ferramenta deve ser simples e gerar relatório imediato.',
    },
    {
        'id': PROJECT_IDS['PROJ_SO_3'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Programa de Mentoria para Startups Industriais',
        'descricao': 'Metodologia de aceleração e mentoria para startups do ecossistema industrial.',
        'trl_entrada': 7,
        'trl_saida': 9,
        'categoria_solucao_resultante': 'Metodologia',
        'modalidade_fomento': 'SEBRAE',
        'edital_fomento': 'Startup Indústria 2024',
        'areas_conhecimento': ['Administração', 'Empreendedorismo'],
        'macroareas_pesquisa': ['Inovação', 'Empreendedorismo'],
        'plataformas_tecnologicas': ['Mentoria', 'Networking'],
        'tematicas': ['Startups', 'Inovação Aberta'],
        'parceiros': [{'nome': 'Endeavor', 'tipo': 'ONG'}],
        'empresa_atendida_tipo': 'Startup',
        'empresa_atendida_nome': 'Cohort de 10 startups',
        'empresa_atendida_cnpj': '',
        'empresa_atendida_cidade': 'Porto Alegre',
        'empresa_atendida_uf': 'RS',
        'empresa_atendida_setor_cnae': 'M71 - Diverso',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2025-03-01',
        'data_fim': '2025-12-31',
        'valor_total': 280000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SO_5']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SO_5']],
        'indicadores': {'startups_aceleradas': 10, 'investimento_captado_m': 5.2},
    },
    {
        'id': PROJECT_IDS['PROJ_SO_4'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Dashboard de Indicadores para Gestão Industrial',
        'descricao': 'Plataforma de BI para visualização de indicadores de desempenho industrial.',
        'trl_entrada': 5,
        'trl_saida': 8,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'FINEP',
        'edital_fomento': 'FINEP IoT 2024',
        'areas_conhecimento': ['Ciência de Dados', 'Administração'],
        'macroareas_pesquisa': ['Business Intelligence', 'Gestão'],
        'plataformas_tecnologicas': ['BI', 'Data Visualization'],
        'tematicas': ['KPIs', 'Gestão à Vista'],
        'parceiros': [{'nome': 'Power BI Partner', 'tipo': 'Empresa'}],
        'empresa_atendida_tipo': 'Média',
        'empresa_atendida_nome': 'Indústrias ABC Ltda',
        'empresa_atendida_cnpj': '91.234.567/0001-45',
        'empresa_atendida_cidade': 'Caxias do Sul',
        'empresa_atendida_uf': 'RS',
        'empresa_atendida_setor_cnae': 'C28.2',
        'empresa_atendida_depoimento': 'Os dashboards transformaram nossa tomada de decisão.',
        'status': 'Concluído',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-02-01',
        'data_fim': '2025-01-31',
        'valor_total': 320000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SO_2']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SO_2']],
        'indicadores': {'indicadores_implementados': 45, 'tempo_decisao_reduzido': 60},
        'licoes_aprendidas': 'Simplicidade na visualização é mais importante que quantidade de dados.',
    },
    {
        'id': PROJECT_IDS['PROJ_SO_5'],
        'instituto_id': INSTITUTE_IDS['CIS_SO'],
        'nome': 'Gamificação para Treinamento em Segurança Industrial',
        'descricao': 'Desenvolvimento de jogos sérios para treinamento de segurança no trabalho.',
        'trl_entrada': 4,
        'trl_saida': 7,
        'categoria_solucao_resultante': 'Software',
        'modalidade_fomento': 'SESI',
        'edital_fomento': 'SESI Saúde e Segurança 2024',
        'areas_conhecimento': ['Educação', 'Design'],
        'macroareas_pesquisa': ['Gamificação', 'Segurança do Trabalho'],
        'plataformas_tecnologicas': ['Games', 'Realidade Virtual'],
        'tematicas': ['Segurança', 'Treinamento'],
        'parceiros': [{'nome': 'SESI-RS', 'tipo': 'Parceiro'}],
        'empresa_atendida_tipo': 'Grande',
        'empresa_atendida_nome': 'Marcopolo S.A.',
        'empresa_atendida_cnpj': '88.611.835/0001-29',
        'empresa_atendida_cidade': 'Caxias do Sul',
        'empresa_atendida_uf': 'RS',
        'empresa_atendida_setor_cnae': 'C29.2',
        'empresa_atendida_depoimento': 'Engajamento no treinamento aumentou 300% com a gamificação.',
        'status': 'Ativo',
        'pode_ser_divulgado': True,
        'data_inicio': '2024-10-01',
        'data_fim': '2026-03-31',
        'valor_total': 580000.00,
        'equipe_ids': [TEAM_IDS['TEAM_SO_3'], TEAM_IDS['TEAM_SO_4']],
        'infraestrutura_ids': [INFRA_IDS['LAB_SO_1'], INFRA_IDS['LAB_SO_3']],
        'indicadores': {'colaboradores_treinados': 2500, 'reducao_acidentes': 35},
    },
]


def _table_exists(conn, table: str) -> bool:
    r = conn.execute(text("SELECT to_regclass(:t)"), {"t": table}).scalar()
    return r is not None


def seed_for_tenant(conn, tenant_id: str) -> None:
    if not _table_exists(conn, "portfolio_projects"):
        print("Skipping portfolio_projects seed: table not present")
        return

    for proj in PORTFOLIO_PROJECTS:
        stmt = text("""
            INSERT INTO portfolio_projects (
                id, tenant_id, instituto_id, nome, descricao, trl_entrada, trl_saida,
                categoria_solucao_resultante, modalidade_fomento, edital_fomento,
                areas_conhecimento, macroareas_pesquisa, plataformas_tecnologicas,
                tematicas, parceiros, empresa_atendida_tipo, empresa_atendida_nome,
                empresa_atendida_cnpj, empresa_atendida_cidade, empresa_atendida_uf,
                empresa_atendida_setor_cnae, empresa_atendida_depoimento,
                status, pode_ser_divulgado, data_inicio, data_fim, valor_total,
                equipe_ids, infraestrutura_ids, indicadores, licoes_aprendidas,
                created_at, updated_at
            )
            SELECT
                :id, :tenant_id, :instituto_id, :nome, :descricao, :trl_entrada, :trl_saida,
                :categoria_solucao_resultante, :modalidade_fomento, :edital_fomento,
                CAST(:areas_conhecimento AS jsonb), CAST(:macroareas_pesquisa AS jsonb),
                CAST(:plataformas_tecnologicas AS jsonb), CAST(:tematicas AS jsonb),
                CAST(:parceiros AS jsonb), :empresa_atendida_tipo, :empresa_atendida_nome,
                :empresa_atendida_cnpj, :empresa_atendida_cidade, :empresa_atendida_uf,
                :empresa_atendida_setor_cnae, :empresa_atendida_depoimento,
                :status, :pode_ser_divulgado, CAST(:data_inicio AS timestamptz), CAST(:data_fim AS timestamptz), :valor_total,
                CAST(:equipe_ids AS jsonb), CAST(:infraestrutura_ids AS jsonb),
                CAST(:indicadores AS jsonb), :licoes_aprendidas,
                now(), now()
            WHERE NOT EXISTS (
                SELECT 1 FROM portfolio_projects WHERE tenant_id = :tenant_id AND id = :id
            )
        """)
        
        conn.execute(stmt, {
            'id': proj['id'],
            'tenant_id': tenant_id,
            'instituto_id': proj['instituto_id'],
            'nome': proj['nome'],
            'descricao': proj['descricao'],
            'trl_entrada': proj.get('trl_entrada'),
            'trl_saida': proj['trl_saida'],
            'categoria_solucao_resultante': proj.get('categoria_solucao_resultante'),
            'modalidade_fomento': proj.get('modalidade_fomento'),
            'edital_fomento': proj.get('edital_fomento'),
            'areas_conhecimento': json.dumps(proj.get('areas_conhecimento', [])),
            'macroareas_pesquisa': json.dumps(proj.get('macroareas_pesquisa', [])),
            'plataformas_tecnologicas': json.dumps(proj.get('plataformas_tecnologicas', [])),
            'tematicas': json.dumps(proj.get('tematicas', [])),
            'parceiros': json.dumps(proj.get('parceiros', [])),
            'empresa_atendida_tipo': proj.get('empresa_atendida_tipo'),
            'empresa_atendida_nome': proj.get('empresa_atendida_nome'),
            'empresa_atendida_cnpj': proj.get('empresa_atendida_cnpj'),
            'empresa_atendida_cidade': proj.get('empresa_atendida_cidade'),
            'empresa_atendida_uf': proj.get('empresa_atendida_uf'),
            'empresa_atendida_setor_cnae': proj.get('empresa_atendida_setor_cnae'),
            'empresa_atendida_depoimento': proj.get('empresa_atendida_depoimento'),
            'status': proj['status'],
            'pode_ser_divulgado': proj.get('pode_ser_divulgado', True),
            'data_inicio': proj.get('data_inicio'),
            'data_fim': proj.get('data_fim'),
            'valor_total': proj.get('valor_total'),
            'equipe_ids': json.dumps(proj.get('equipe_ids', [])),
            'infraestrutura_ids': json.dumps(proj.get('infraestrutura_ids', [])),
            'indicadores': json.dumps(proj.get('indicadores', {})),
            'licoes_aprendidas': proj.get('licoes_aprendidas'),
        })

    print(f"portfolio_projects seed applied for tenant: {tenant_id}")


def seed_for_tenants(conn, tenant_ids: Iterable[str]) -> None:
    for t in tenant_ids:
        seed_for_tenant(conn, t)
